ARG VERSION=safety-checker
FROM public.ecr.aws/i0t3i1w9/stable-diffusion-server:${VERSION}

# Get just the controlnet models we want to launch with
# Canny
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15_canny', True);"

# Depth
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11f1p_sd15_depth', True);"

# Normalbae
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15_normalbae', True);"

# Openpose
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15_openpose', True);"

# Scribble
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15_scribble', True);"

# Softedge
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15_softedge', True);"

# Lineart
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15_lineart', True);"

# Lineart Anime
RUN python -c "from server.model_loaders import load_controlnet_model_from_hf; load_controlnet_model_from_hf('lllyasviel/control_v11p_sd15s2_lineart_anime', True);"

# QR Code
RUN python -c "from server.model_loaders import load_controlnet_model_from_civitai; load_controlnet_model_from_civitai('122143', True);"

ENV HF_CONTROLNET_MODELS="lllyasviel/control_v11p_sd15_canny,lllyasviel/control_v11f1p_sd15_depth,lllyasviel/control_v11p_sd15_normalbae,lllyasviel/control_v11p_sd15_openpose,lllyasviel/control_v11p_sd15_scribble,lllyasviel/control_v11p_sd15_softedge,lllyasviel/control_v11p_sd15_lineart,lllyasviel/control_v11p_sd15s2_lineart_anime"
ENV CIVITAI_CONTROLNET_MODELS="122143"