services:
  stable-diffusion-service:
    image: public.ecr.aws/i0t3i1w9/stable-diffusion-server:lykon-dreamshaper-controlnet-slim
    # runtime: nvidia
    network_mode: host
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.base
    ports:
      - "1111:1111"
    environment:
      - HOST=*
      - PORT=1111
      - MODEL_DIR=/models
      - MODELS=Lykon/DreamShaper
      - CONTROLNET_MODELS=canny,depth,normal,openpose,scribble,softedge,lineart,lineart_anime,qr_code
    # volumes:
    #   - /models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    