ARG VERSION=base
FROM public.ecr.aws/i0t3i1w9/stable-diffusion-server:${VERSION}

ARG HF_SAFETY_CHECKER="CompVis/stable-diffusion-safety-checker"
ARG HF_CLIP_MODEL="openai/clip-vit-base-patch32"
ENV HF_SAFETY_CHECKER=${HF_SAFETY_CHECKER}
ENV HF_CLIP_MODEL=${HF_CLIP_MODEL}
ENV MODEL_DIR=/models

RUN python -c "from server.model_loaders import load_safety_checker; load_safety_checker(True);"