ARG BASE_TAG=controlnet-full

FROM public.ecr.aws/i0t3i1w9/stable-diffusion-server:${BASE_TAG}

ARG HF_REPO=Lykon/DreamShaper

RUN python -c "from server.model_loaders import load_checkpoint_from_hf; load_checkpoint_from_hf('${HF_REPO}', True);"

ENV HF_CHECKPOINTS=${HF_REPO}