services:
  stable-diffusion-service:
    image: public.ecr.aws/i0t3i1w9/stable-diffusion-server:0.3.0
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.base
    ports:
      - "1111:1111"
    environment:
      - HOST=*
      - PORT=1111
      - CIVITAI_CONTROLNET_MODELS=122143
      - CIVITAI_CHECKPOINTS=128713
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
