services:
  stable-diffusion-service:
    image: public.ecr.aws/i0t3i1w9/stable-diffusion-server:base-models
    # runtime: nvidia
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile.base-models
    ports:
      - "1111:1111"
    environment:
      - HOST=*
      - PORT=1111
      - MODEL_DIR=/models
      - MODELS=Lykon/DreamShaper
    volumes:
      - /models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    