#! /usr/bin/env bash

MODEL_ID=$1

# Lowercase, replace / with -, and remove all other non-alphanumeric characters
MODEL_TAG=$(echo $MODEL_ID | tr '[:upper:]' '[:lower:]' | tr '/' '-')

sudo mkdir -p ./models/$MODEL_ID

# If the directory is empty, copy the model from EFS
if [ -z "$(ls -A ./models/$MODEL_ID)" ]; then
    echo "Copying model from EFS"
    sudo cp -r /models/$MODEL_ID/ ./models/$MODEL_ID/
fi

docker build \
-t public.ecr.aws/i0t3i1w9/stable-diffusion-server:$MODEL_TAG \
--build-arg MODEL_ID=$MODEL_ID \
-f Dockerfile.model .