#! /usr/bin/env bash

MODEL_ID=$1

# Lowercase, replace / with -, and remove all other non-alphanumeric characters
MODEL_TAG=$(echo $MODEL_ID | tr '[:upper:]' '[:lower:]' | tr '/' '-')

mkdir -p ./models/$MODEL_ID
ln -s /models/$MODEL_ID ./models/$MODEL_ID

docker build \
-t public.ecr.aws/i0t3i1w9/stable-diffusion-server:$MODEL_TAG \
--build-arg MODEL_ID=$MODEL_ID \
-f Dockerfile.model .