#! /usr/bin/env bash
PYTHON=$(which python3 || which python)
VERSION=$($PYTHON -c 'from server.__version__ import VERSION; print(VERSION)')

docker buildx build \
  -t public.ecr.aws/i0t3i1w9/stable-diffusion-server:safety-checker \
  -f Dockerfile.safety \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  --build-arg VERSION=$VERSION \
  .
docker tag public.ecr.aws/i0t3i1w9/stable-diffusion-server:safety-checker \
  public.ecr.aws/i0t3i1w9/stable-diffusion-server:$VERSION-safety-checker
