#! /usr/bin/env bash
PYTHON=$(which python3 || which python)
VERSION=$($PYTHON -c 'from server.__version__ import VERSION; print(VERSION)')

docker build -t public.ecr.aws/i0t3i1w9/stable-diffusion-server:controlnet-slim -f Dockerfile.controlnet-slim .
docker tag public.ecr.aws/i0t3i1w9/stable-diffusion-server:controlnet-slim \
  public.ecr.aws/i0t3i1w9/stable-diffusion-server:$VERSION-controlnet-slim