#! /usr/bin/env bash
PYTHON=$(which python3 || which python)
VERSION=$($PYTHON -c 'from server.__version__ import VERSION; print(VERSION)')

docker build \
  -t public.ecr.aws/i0t3i1w9/stable-diffusion-server:base \
  -f Dockerfile.base \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  .
docker tag public.ecr.aws/i0t3i1w9/stable-diffusion-server:base \
  public.ecr.aws/i0t3i1w9/stable-diffusion-server:$VERSION
