#! /usr/bin/env bash

curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | sudo bash
sudo amazon-linux-extras install epel -y
sudo yum update -y
sudo yum install git-lfs -y
# git lfs install