#! /usr/bin/env bash

MODEL_ID=$1

# Lowercase, replace / with -, and remove all other non-alphanumeric characters
MODEL_TAG=$(echo $MODEL_ID | tr '[:upper:]' '[:lower:]' | tr '/' '-')

ln -s /models/$MODEL_ID ./models/$MODEL_ID

docker push public.ecr.aws/i0t3i1w9/stable-diffusion-server:$MODEL_TAG