#! /usr/bin/env bash
PYTHON=$(which python3 || which python)
VERSION=$($PYTHON -c 'from server.__version__ import VERSION; print(VERSION)')

docker push public.ecr.aws/i0t3i1w9/stable-diffusion-server:nitrosocke-nitro-diffusion-controlnet-slim
docker push public.ecr.aws/i0t3i1w9/stable-diffusion-server:$VERSION-nitrosocke-nitro-diffusion-controlnet-slim